### ISSUE TITLE
YAML Config for multi repo projects

### ISSUE THREAD

**Issue by ahstn** [ahstn/atlas#11]
atlas should be able to read a config file that declares projects to be built.

Requirements:
* Multiple repos/projects
* Custom Git folder
* Using docker for build (with custom build args(?) and image)
* Using docker to run app (with custom args)

Example:
```yaml
---
base_dir: '~/git'
projects:
  - name: auth
    repo: https://github.com/ahstn/auth
    tasks: 
      - build
      - package
    docker:
      build:
        enabled: true
        args: ''
        image: mvn:latest
        target: auth:1.3.0
      run:
        args: '-p 8080:80'
  - name: gateway
    repo: ssh://git@github.com/ahstn/gateway
    tasks: 
      - build
      - package
    docker:
      build:
        enabled: false
      run:
        args: '-p 8080:80 -e environment="dev"'
```

Command for now:
```bash
atlas project -c atlas.yaml
```
