### ISSUE TITLE
Allow Docker Builds in YAML Config

### ISSUE THREAD

**Issue by ahstn** [ahstn/atlas#18]
Continuing on from #11 : Adding the ability to have docker builds associated with projects.

User's should have the ability to:
* Specify Dockerfile location (In project repo or elsewhere)
* Set a build image to use
* Add arguments that should be passed to Docker
* Set specific tags
  * It may also make sense to have a global docker tag for the repo (i.e k8s.gcr.io)

Also following the same config structure:
```yaml
---
base_dir: '~/git'
projects:
  - name: auth
    repo: https://github.com/ahstn/auth
    tasks: 
      - build
      - package
    docker:
      build:
        enabled: true
        args: ''
        image: mvn:latest
        target: auth:1.3.0
      run:
        args: '-p 8080:80'

```
