### ISSUE TITLE
Allow Docker Runs in YAML Config

### ISSUE THREAD

**Issue by ahstn** [ahstn/atlas#24]
Continuing on from #11 and linked to #18 : Allowing applications to have Docker runs associated with them.

Users should have the ability to:
* Enable/disabled feature
* Have a command for just running apps using Docker
* Add arguments that should be passed to Docker
  * This should probably be an array to avoid a messy, long string
  * Specifying environment variables should be seperate
* Override command/entrypoint

Following the same config structure:
```yaml
---
base_dir: '~/git'
projects:
  - name: auth
    repo: https://github.com/ahstn/auth
    tasks: 
      - build
    docker:
      build:
        enabled: true
      run:
        enabled: true
        args: 
          - '-p 8080:80'
        env:
          - USER=ahstn
        entrypoint: '/bin/bash'
```

Command for now:
```bash
atlas project --docker-run
```
