### ISSUE TITLE
Allow apps to be grouped in config

### ISSUE THREAD

**Issue by ahstn** [ahstn/atlas#36]
Similar idea to #15.

This would allow users to specify a group of applications/services to run a command against rather than everything.

Thought process behind this is if an entire stack is 6 apps (as defined in config), but the developer's current code change only affects 2 of those 6. Then they should only need to re-build and run those 2 apps rather than all 6. Implementing this feature will be a QoL improvement when doing this.

Again, probably similar to how #15 will be implemented, in that like [Docker Compose](https://docs.docker.com/compose/compose-file/#depends_on), have a field under each service that specifies a group name.

Config Change:
```yaml
-
  name: auth
  repo: https://github.com/ahstn/atlas
  tasks:
    -  build
  group: core
```

Command flag:
```sh
atlas docker --config 'atlas.yaml' --group 'core'
```
